### ISSUE TITLE
I'd like to hire you for some help

### ISSUE THREAD

**Issue by Raylee1** [arch4ngel/simple_https_server#1]
Hi @arch4ngel 

I am currently working on a golang project and I'm wondering if you can help me perhaps. I have tried freelancing sites but there doesn't seem to be many golang developers.

Is there any other way I can get in contact with you?

**Comment by ImpostorKeanu** [comment]
Hi @Raylee1 ,

I do not have the bandwidth to help with development projects outside of my full time gig. Thanks for inquiring.
